services:
  spark-notebook:
    image: jupyter/pyspark-notebook:latest
    container_name: pyspark-notebook
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - .:/home/jero/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=unad123